---
bundler_args: '--without system_tests'
cache: 'bundler'
language: 'ruby'
script: 'bundle exec rake spec'

env:
  - PUPPET_GEM_VERSION='~> 4.7.0'
  - PUPPET_GEM_VERSION='~> 4.8.0'
  - PUPPET_GEM_VERSION='~> 4.9.0'
  - PUPPET_GEM_VERSION='~> 4.10.0'
  - PUPPET_GEM_VERSION='~> 5.0.0'
rvm:
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1

matrix:
  fast_finish: true
  exclude:
    - env: PUPPET_GEM_VERSION='~> 4.7.0'
      rvm: 2.4.1
  include:
    - env: ''
      rvm: 2.4.1
      script: 'bundle exec rake'

    - env: 'DEPLOY=yes'
      rvm: 2.4.1
      script:
        - 'bundle exec rake build'
        - 'bundle exec rake strings:generate'

    # Beaker
    - bundler_args: '--with system_tests'
      env: 'PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-1604'
      rvm: 2.4.1
      script: 'bundle exec rake beaker'
      services: 'docker'
    - bundler_args: '--with system_tests'
      env: 'ORDERING=random PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-1604'
      rvm: 2.4.1
      script: 'bundle exec rake beaker'
      services: 'docker'

deploy:
  - provider: 'puppetforge'
    user: 'joshuaspence'
    password: '$PUPPET_FORGE_PASSWORD'
    on:
      condition: '$DEPLOY = yes'
      tags: true

  - provider: 'pages'
    github_token: '$GITHUB_TOKEN'
    local_dir: 'doc'
    skip_cleanup: true
    on:
      condition: '$DEPLOY = yes'
      tags: true
