name 'joshuaspence-phabricator'
version '0.1.0'
source 'http://github.com/joshuaspence/vagrant-phabricator/tree/master/puppet-phabricator'
author 'Joshua Spence'
license 'Apache 2.0'
summary 'Phabricator module'
description 'Phabricator module'
project_page 'http://github.com/joshuaspence/vagrant-phabricator'

dependency 'jfryman/nginx', '>= 0.0.7'
dependency 'puppetlabs/mysql', '>= 2.2.1'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/vcsrepo', '>= 0.2.0'
dependency 'thias/php', '>= 0.3.9'
